services:
  openmower:
    # OpenMowerOSv2 needs an image with `-osv2` suffix
    image: "${REPO}:${VERSION}-osv2"
    container_name: openmower
    privileged: true
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mosquitto
    volumes:
      - /dev:/dev
      - /home/openmower:/root
      - /home/openmower/mower_params.yaml:/config/mower_params.yaml
      - type: volume
        source: openmower_web
        target: /opt/open_mower_ros/web
    environment:
      DEBUG: $DEBUG
      OM_V2: $V2_HARDWARE
      OM_MOWER: $MOWER
  
  # MQTT broker for OpenMower
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  # Nginx to serve the OpenMower web assets
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - openmower
    volumes:
      - type: volume
        source: openmower_web
        target: /usr/share/nginx/html
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

volumes:
  openmower_web: {}

# Dockge-specific extras shown in the UI
x-dockge:
  urls:
  - http://${HOSTNAME}:8080
  - ws://${HOSTNAME}:9001
