version: "3.9"

# Compose stack for OpenMower.
# The image tag is controlled via /etc/default/openmower by OM_VERSION (and optionally OM_IMAGE).

services:
  openmower:
    image: ${OM_IMAGE}
    container_name: openmower
    tty: true
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - /home/openmower/mower_config.sh:/config/mower_config.sh:ro
      - /home/openmower:/root
    environment:
      ROSOUT_DISABLE_FILE_LOGGING: "True"
