#!/bin/bash -e

# This runs outside chroot with ROOTFS_DIR pointing at target root filesystem.
# We can access the git repo to extract commit hash and describe.

STAGE_DIR="$(dirname "$0")"
REPO_ROOT="$(cd "$STAGE_DIR/../.." && pwd)"
OUT_DIR="$ROOTFS_DIR/usr/share/openmoweros"

echo "Creating output directory $OUT_DIR"
mkdir -p "$OUT_DIR"

# Extract git metadata from injected environment variables (set in build_image.sh). Fall back to unknown.
GIT_HASH="${OMOS_GIT_HASH:-unknown}"
GIT_HASH_FULL="${OMOS_GIT_HASH_FULL:-unknown}"
GIT_DESCRIBE="${OMOS_GIT_DESCRIBE:-unknown}"
GIT_BRANCH="${OMOS_GIT_BRANCH:-unknown}"
BUILD_TIME_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Source pi-gen.config to get image variables
CFG_FILE="$REPO_ROOT/pi-gen.config"
if [ -f "$CFG_FILE" ]; then
    # shellcheck disable=SC1090
    source "$CFG_FILE"
fi

# Provide sane defaults if not set
: "${IMG_NAME:=OpenMowerOS}"
: "${PI_GEN_RELEASE:=unknown}"
: "${RELEASE:=unknown}"
: "${ARCH:=unknown}"

# Version string heuristics
DISPLAY_VERSION="${PI_GEN_RELEASE}"
echo "IMG_NAME=${IMG_NAME} DISPLAY_VERSION=${DISPLAY_VERSION} RELEASE=${RELEASE} ARCH=${ARCH}"
echo "Git: hash=${GIT_HASH} describe=${GIT_DESCRIBE} branch=${GIT_BRANCH}"

# Write a machine-readable JSON
echo "Writing version.json"
cat >"$OUT_DIR/version.json" <<EOF
{
  "name": "${IMG_NAME}",
  "display_version": "${DISPLAY_VERSION}",
  "release": "${RELEASE}",
  "arch": "${ARCH}",
  "git": {
    "hash": "${GIT_HASH}",
    "hash_full": "${GIT_HASH_FULL}",
    "describe": "${GIT_DESCRIBE}",
    "branch": "${GIT_BRANCH}"
  },
  "build_time_utc": "${BUILD_TIME_UTC}"
}
EOF

# YAML variant
echo "Writing version.yaml"
cat >"$OUT_DIR/version.yaml" <<EOF
# Auto-generated OpenMowerOS build metadata
name: ${IMG_NAME}
display_version: ${DISPLAY_VERSION}
release: ${RELEASE}
arch: ${ARCH}
git:
  hash: ${GIT_HASH}
  hash_full: ${GIT_HASH_FULL}
  describe: ${GIT_DESCRIBE}
  branch: ${GIT_BRANCH}
build_time_utc: ${BUILD_TIME_UTC}
EOF

# Shell export variant (source this to populate OPENMOWEROS_* variables)
echo "Writing version.sh"
cat >"$OUT_DIR/version.sh" <<EOF
# shellcheck shell=bash
# Autogenerated OpenMowerOS build metadata. Do not edit; regenerated at image build time.
OPENMOWEROS_NAME=${IMG_NAME@Q}
OPENMOWEROS_DISPLAY_VERSION=${DISPLAY_VERSION@Q}
OPENMOWEROS_RELEASE=${RELEASE@Q}
OPENMOWEROS_ARCH=${ARCH@Q}
OPENMOWEROS_GIT_HASH=${GIT_HASH@Q}
OPENMOWEROS_GIT_HASH_FULL=${GIT_HASH_FULL@Q}
OPENMOWEROS_GIT_DESCRIBE=${GIT_DESCRIBE@Q}
OPENMOWEROS_GIT_BRANCH=${GIT_BRANCH@Q}
OPENMOWEROS_BUILD_TIME_UTC=${BUILD_TIME_UTC@Q}
EOF

# Human readable issue-like file (similar to /etc/rpi-issue). First line concise.
echo "Writing version.txt"
cat >"$OUT_DIR/version.txt" <<EOF
# OpenMowerOS version summary (auto-generated)
${IMG_NAME} ${DISPLAY_VERSION} (${RELEASE} ${ARCH})
Git: ${GIT_DESCRIBE} (${GIT_HASH}) on ${GIT_BRANCH}
Built: ${BUILD_TIME_UTC} UTC
EOF

# Permissions
chmod 0644 "$OUT_DIR"/version.*
echo "Done. Files: $(ls -1 $OUT_DIR | xargs)"

