services:
  webterminal:
    image: tsl0922/ttyd:alpine
    container_name: webterminal
    # privileged: true   # Uncomment only if you really need full host device access
    # pid: host          # Uncomment with privileged for full host PID namespace
    network_mode: host
    restart: unless-stopped
    volumes:
      - /:/host
      - /home/openmower/.bash_history:/home/openmower/.bash_history
    command: >
      sh -c 'ttyd --client-option disableReconnect=true --client-option disableLeaveConfirmation=true --writable --port ${TTYD_PORT} --credential ${TTYD_USER}:${TTYD_PASS} \
        chroot /host /usr/local/sbin/webterminal-shell-wrapper.sh'

# Dockge-specific extras shown in the UI
x-dockge:
  urls:
  - http://${HOSTNAME}:${TTYD_PORT}
