#!/bin/bash -e

# Append commented examples to Raspberry Pi config.txt under the [all] section.
# - Fan control (gpio-fan overlay)
# - CM4 antenna selection (ant1/ant2)

add_examples() {
    local f="$1"
    [ -e "$f" ] || return 0
    
    # Respect images that declare this file as "DO NOT EDIT ..."
    if grep -Fq "DO NOT EDIT THIS FILE" "$f"; then
        return 0
    fi
    
    # Ensure [all] section exists
    if ! grep -q '^\[all\]' "$f"; then
        echo >> "$f"
        echo "[all]" >> "$f"
    fi
    
    # Add our examples only once (match current marker header)
    if grep -q '^# OpenMowerOS specific$' "$f"; then
        return 0
    fi
    
    cat >> "$f" <<'EOF'

#
# OpenMowerOS specific
#

# Fan control (GPIO fan) — enable and set start temperature (in millidegrees C)
# Example: enable GPIO fan on GPIO6, start at 70°C:
# dtoverlay=gpio-fan,gpiopin=6,temp=70000

# CM4 antenna selection — choose Wi‑Fi antenna path
# Internal/on‑module antenna (default):
# dtparam=ant1
# External- U.FL/IPEX antenna connector:
# dtparam=ant2
EOF
}

# Handle both possible locations across releases
add_examples /boot/firmware/config.txt || true
add_examples /boot/config.txt || true

exit 0
