#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

echo "Get socat for GPS redirection (debug port)"
apt install socat


#unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

echo "This is an example module, install and set up what you need here!"
echo "$OPENMOWEROS_VAR"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /



# Enable the UARTs for OpenMower
echo "dtoverlay=disable-bt\
dtoverlay=uart2\
dtoverlay=uart3\
dtoverlay=uart4\
dtoverlay=uart5" >> /boot/config.txt

# Remove the serial console from cmdline.txt.
sed -i 's/console=serial0,115200 //g' cmdline.txt
