#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

echo "Get socat for GPS redirection (debug port)"
apt install socat

unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

echo "This is an example module, install and set up what you need here!"
echo "$OPENMOWEROS_VAR"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /



# Enable the UARTs for OpenMower
echo "dtoverlay=disable-bt
dtoverlay=uart2
dtoverlay=uart3
dtoverlay=uart4
dtoverlay=uart5" >> /boot/config.txt

# Remove the serial console from cmdline.txt.
sed -i 's/console=serial0,115200 //g' /boot/cmdline.txt

wget -O /boot/mower_config.sh https://raw.githubusercontent.com/ClemensElflein/open_mower_ros/main/src/open_mower/config/mower_config.sh.example

# enable the open-mower service
systemctl enable open-mower
